name = {
    "StoneTool": "石製工具",
    "BronzeTool": "青銅製工具",
    "IronTool": "鐵製工具",
    "SteelTool": "鋼製工具",
    "SteamPower": "蒸汽動力",
    "ElectronicTechnology": "電子科技",
    "Religion": "宗教",
    "Chiefdom": "酋邦",
    "Feudal": "封建",
    "Centralization": "集權",
    "Democracy": "民主",
    "Theocracy": "神權政治",
    "Monarchy": "王權",
    "Empire": "帝國",
    "Totalitarian": "極權",
    "PermanentMember": "常任理事國",
    "Wheat": "小麥",
    "Alcohol": "酒",
    "Meat": "肉",
    "Fish": "魚",
    "GatheringAndHunting": "採集狩獵",
    "Fishery": "漁業",
    "Writing": "竹簡",          
    "Book": "手抄書",
    "Printing": "印刷術",
    "Currency": "銅錢",
    "Trading": "商業",
    "Industrialization": "工業",
}

disc = {
    "StoneTool": "(小麥產量,竹簡產量)+擁有個數",
    "BronzeTool": "(小麥產量,竹簡產量)+2*擁有個數",
    "IronTool": "(小麥產量,竹簡產量)+3*擁有個數",
    "SteelTool": "(小麥產量,竹簡產量)+4*擁有個數",
    "SteamPower": "(小麥產量,竹簡產量)+5*擁有個數",
    "ElectronicTechnology": "(小麥產量,竹簡產量)+6*擁有個數",
    "Religion": "青銅製工具產量+擁有個數",
    "Chiefdom": "石製工具產量+擁有個數",
    "Feudal": "鐵製工具產量+擁有個數",
    "Centralization": "鋼製工具產量+擁有個數",
    "Democracy": "鋼製工具產量+擁有個數",
    "Theocracy": "蒸汽製工具產量+擁有個數",
    "Monarchy": "酋邦/5 = 王權個數",
    "Empire": "蒸汽製工具產量+擁有個數",
    "Totalitarian": "蒸汽製工具產量+擁有個數",
    "PermanentMember": "蒸汽製工具產量+擁有個數",
    "Wheat": "對，這是小麥，可以增加人口數。",
    "Alcohol": "小麥/3 = 酒個數",
    "Meat": "就是肉，可以增加人口數。",
    "Fish": "就是魚，可以增加人口數。",
    "GatheringAndHunting": "用來獲得肉",
    "Fishery": "用來獲得魚",
    "Writing": "竹簡可以讓識字率小幅度提高",          
    "Book": "手抄書可以讓識字率提高",
    "Printing": "印刷術可以讓識字率大幅提高",
    "Currency": "錢是文明的開始",
    "Trading": "金錢就是力量",
    "Industrialization": "工業革命",
}

while 1:
    s = input()
    id = s[4:-1]
    # print(f'''"{id}": "{id}",''')
    print(f'''
        (((1, 1)), (
            id: {id},
            name: "{name[id]}",
            description: "{disc[id]}",
            texture_id: {id},
        )),''',end='')